language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-dev
    - sudo apt-get install $PYTHON-setuptools
    - sudo pip-$PYVER install cython
    - sudo $PYTHON setup.py install
# command to run tests
script: pytest
